Building the AWS infrastructure

diff --git a/.github/workflows/argocd.yaml b/.github/workflows/argocd.yaml
--- a/.github/workflows/argocd.yaml
+++ b/.github/workflows/argocd.yaml
@@ -16,9 +16,27 @@ jobs:
           aws-access-key-id: ${{ secrets.ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
           aws-region: us-east-1
+      - name: Install Argo CD CLI
+        run: |
+          
+            if ! command -v argocd &> /dev/null; then
+              echo "ArgoCD not found. Installing..."
+              curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+              chmod +x argocd
+              sudo mv argocd /usr/local/bin/
+              argocd version --client
+      
+            else
+              echo "ArgoCD is already installed."
+            fi
       - name: login to argocd CLI
         run:
           argocd login ${{ vars.ARGOCD_URL }} --username ${{ vars.ARGOCD_USER}} --password ${{ secrets.ARGICD_PASSWORD}} --insecure
+      - name: helm registry login
+        run: |
+          helm registry login ghcr.io \
+            -u ${{ vars.HELM_USERNAME}} \
+            -p ${{ secrets.TOKEN}}
       - name : create repo on github registry
         run: |
           argocd repo add ghcr.io/belalkhaledmohameed --type helm --name githubhelm   --enable-oci  --username  ${{ vars.HELM_USERNAME }} --password ${{ secrets.TOKEN }}   --core --upsert
